configured_endpoints: 1387
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/bluestaq%2Funifieddatalibrary-5dbde69014a90286be866c9590f4a10a2cf6dc50796206a9a2c7b169c7526b39.yml
