configured_endpoints: 483
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/bluestaq%2Funifieddatalibrary-7f128496d6dcf8be143dbfb49c8b37deb95821d3fb119e81562a697c5cc6e086.yml
