configured_endpoints: 1379
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/bluestaq%2Funifieddatalibrary-53ced4917cd15169f8003b5b804a03c032dcc518156d0526b62c79a1e55a5dfe.yml
