configured_endpoints: 483
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/bluestaq%2Funifieddatalibrary-0f35a717d30bd601443eaf1b6604a43e8b0d8932ee2cd1b4f2e5bdd91d86021a.yml
