# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import List, Union, Iterable
from datetime import datetime
from typing_extensions import Literal, Required, Annotated, TypedDict

from ..._utils import PropertyInfo

__all__ = ["GnssrawifCreateParams"]


class GnssrawifCreateParams(TypedDict, total=False):
    center_freq: Required[Annotated[Iterable[float], PropertyInfo(alias="centerFreq")]]
    """The center frequency, in MHz, of the observation bands.

    More than one band may be reported in each binary file, so this is an array of
    the center frequency of each band (including an array of length 1 if only one
    band is present).
    """

    classification_marking: Required[Annotated[str, PropertyInfo(alias="classificationMarking")]]
    """Classification marking of the data in IC/CAPCO Portion-marked format."""

    data_mode: Required[Annotated[Literal["REAL", "TEST", "SIMULATED", "EXERCISE"], PropertyInfo(alias="dataMode")]]
    """Indicator of whether the data is EXERCISE, REAL, SIMULATED, or TEST data:

    EXERCISE:&nbsp;Data pertaining to a government or military exercise. The data
    may include both real and simulated data.

    REAL:&nbsp;Data collected or produced that pertains to real-world objects,
    events, and analysis.

    SIMULATED:&nbsp;Synthetic data generated by a model to mimic real-world
    datasets.

    TEST:&nbsp;Specific datasets used to evaluate compliance with specifications and
    requirements, and for validating technical, functional, and performance
    characteristics.
    """

    end_time: Required[Annotated[Union[str, datetime], PropertyInfo(alias="endTime", format="iso8601")]]
    """
    End time of the data contained in the associated binary file, in ISO 8601 UTC
    format with microsecond precision.
    """

    file_name: Required[Annotated[str, PropertyInfo(alias="fileName")]]
    """The file name of the Raw IF Binary file.

    The files should be in the Hierarchical Data Format (HDF5).
    """

    source: Required[str]
    """Source of the data."""

    start_time: Required[Annotated[Union[str, datetime], PropertyInfo(alias="startTime", format="iso8601")]]
    """
    Start time of the data contained in the associated binary file, in ISO 8601 UTC
    format with microsecond precision.
    """

    id: str
    """Unique identifier of the record, auto-generated by the system."""

    bit_depth: Annotated[int, PropertyInfo(alias="bitDepth")]
    """
    The number of bits in each datum, for example 2 for 2-bit integers or 8 for
    8-bit integers.
    """

    boresight: Iterable[float]
    """
    Unit vector of the outward facing direction of the receiver boresight in a
    body-fixed coordinate system.
    """

    data_rate: Annotated[float, PropertyInfo(alias="dataRate")]
    """The amount of data generated per unit time, expressed in Megabytes/minute."""

    diff_code_bias: Annotated[Iterable[float], PropertyInfo(alias="diffCodeBias")]
    """
    Differential Code Biases (DCBs) are the systematic errors, or biases, between
    two GNSS code observations at the same or different frequencies. If applicable,
    this field should contain an array of DBC with length equal to the number of
    frequencies in the binary file. The reference frequency should show DCB equal
    to 0. If null, it is assumed that there is no DCB (all values are 0).
    """

    end_alt: Annotated[float, PropertyInfo(alias="endAlt")]
    """
    Spacecraft altitude at end time (endTime), expressed in kilometers above WGS-84
    ellipsoid.
    """

    end_lat: Annotated[float, PropertyInfo(alias="endLat")]
    """
    WGS-84 spacecraft latitude sub-point at end time (endTime), represented as -90
    to 90 degrees (negative values south of equator).
    """

    end_lon: Annotated[float, PropertyInfo(alias="endLon")]
    """
    WGS-84 spacecraft longitude sub-point at end time (endTime), represented as -180
    to 180 degrees (negative values west of Prime Meridian).
    """

    es_id: Annotated[str, PropertyInfo(alias="esId")]
    """
    Unique identifier of the parent Ephemeris Set, if this data is correlated with
    an Ephemeris. If reporting for a spacecraft with multiple onboard GNSS
    receivers, this ID may be associated with multiple GNSS Raw IF records if each
    receiver is synced to the ephemeris points.
    """

    event_id: Annotated[str, PropertyInfo(alias="eventId")]
    """Optional source-provided identifier for this collection event.

    This field can be used to associate records related to the same event.
    """

    if_freq: Annotated[Iterable[float], PropertyInfo(alias="ifFreq")]
    """The center frequency, in MHz, after downconversion to intermediate frequency.

    If provided, this array should have the same length as centerFreqs.
    """

    origin: str
    """
    Originating system or organization which produced the data, if different from
    the source. The origin may be different than the source if the source was a
    mediating system which forwarded the data on behalf of the origin system. If
    null, the source may be assumed to be the origin.
    """

    orig_object_id: Annotated[str, PropertyInfo(alias="origObjectId")]
    """
    Optional identifier provided by the data source to indicate the target object of
    this record. This may be an internal identifier and not necessarily map to a
    valid satellite number.
    """

    post_fourier: Annotated[List[str], PropertyInfo(alias="postFourier")]
    """
    After converting the raw data in the file, to generate (frequency-space) spectra
    some sets require an additional transformation or correction based on details of
    the hardware that recorded it. This field marks any such transformations.
    Currently supported options are NONE (no correction) and MIRRORED (frequency
    axis is flipped around the corresponding value of ifFreq). If null, it is
    assumed that NONE applies to all frequency bands.
    """

    quat: Iterable[float]
    """
    The quaternion describing the rotation of the body-fixed frame used for this
    system into the local geodetic frame, at the sample start time (startTime). The
    array element order convention is scalar component first, followed by the three
    vector components. For a vector u in the body-fixed frame, the corresponding
    vector u' in the geodetic frame should satisfy u' = quq\\**, where q is this
    quaternion. The quaternion should be normalized to 1.
    """

    receiver: str
    """The number or ID of the GNSS receiver associated with this data.

    If reporting for multiple receivers a separate record should be generated for
    each. If null, it is assumed to indicate that only one receiver is present, or
    reported.
    """

    sample_rate: Annotated[Iterable[int], PropertyInfo(alias="sampleRate")]
    """The number of samples taken per second."""

    sample_type: Annotated[str, PropertyInfo(alias="sampleType")]
    """The sample type associated with the IF data.

    REAL for data with only an I-component or COMPLEX for data with both I & Q
    components.
    """

    sat_no: Annotated[int, PropertyInfo(alias="satNo")]
    """Satellite/catalog number of the target on-orbit object."""

    sequence_id: Annotated[int, PropertyInfo(alias="sequenceID")]
    """The sequence number of a raw IF record/file within a set.

    Sequence number should start at 1. If null, then it is assumed that the order of
    records within a raw IF set is not relevant.
    """

    set_id: Annotated[str, PropertyInfo(alias="setId")]
    """User-defined ID of a set or sequence of records/files.

    Used to associate a set of related raw IF records.
    """

    set_length: Annotated[int, PropertyInfo(alias="setLength")]
    """The number of raw IF records/files in a set."""

    src_ids: Annotated[List[str], PropertyInfo(alias="srcIds")]
    """Array of UUIDs of the UDL data records associated with this GNSSRawIF record.

    See the associated 'srcTyps' array for the specific types of data, positionally
    corresponding to the UUIDs in this array. The 'srcTyps' and 'srcIds' arrays must
    match in size. See the corresponding srcTyps array element for the data type of
    the UUID and use the appropriate API operation to retrieve that object (e.g.
    /udl/gnssobservationset/{uuid}).
    """

    src_typs: Annotated[List[str], PropertyInfo(alias="srcTyps")]
    """Array of UDL record types (GNSSSET) associated with this GNSSRawIF record.

    See the associated 'srcIds' array for the record UUIDs, positionally
    corresponding to the record types in this array. The 'srcTyps' and 'srcIds'
    arrays must match in size.
    """

    start_alt: Annotated[float, PropertyInfo(alias="startAlt")]
    """
    Spacecraft altitude at start time (startTime), expressed in kilometers above
    WGS-84 ellipsoid.
    """

    start_index: Annotated[int, PropertyInfo(alias="startIndex")]
    """
    The index of the sample within the associated binary file that corresponds to
    the startTime indicated in this record. This is especially useful on high
    sample-rate sensors when some samples are less than one microsecond before the
    value of startTime. This index is 0-based. If null, the startIndex is assumed to
    be 0.
    """

    start_lat: Annotated[float, PropertyInfo(alias="startLat")]
    """
    WGS-84 spacecraft latitude sub-point at start time (startTime), represented as
    -90 to 90 degrees (negative values south of equator).
    """

    start_lon: Annotated[float, PropertyInfo(alias="startLon")]
    """
    WGS-84 spacecraft longitude sub-point at start time (startTime), represented as
    -180 to 180 degrees (negative values west of Prime Meridian).
    """

    tags: List[str]
    """
    Optional array of provider/source specific tags for this data, where each
    element is no longer than 32 characters, used for implementing data owner
    conditional access controls to restrict access to the data. Should be left null
    by data providers unless conditional access controls are coordinated with the
    UDL team.
    """
