# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import List, Optional
from datetime import datetime
from typing_extensions import Literal

from pydantic import Field as FieldInfo

from ...._compat import PYDANTIC_V2
from ...._models import BaseModel

__all__ = ["OrbitdeterminationFull"]


class OrbitdeterminationFull(BaseModel):
    classification_marking: str = FieldInfo(alias="classificationMarking")
    """Classification marking of the data in IC/CAPCO Portion-marked format."""

    data_mode: Literal["REAL", "TEST", "SIMULATED", "EXERCISE"] = FieldInfo(alias="dataMode")
    """Indicator of whether the data is EXERCISE, REAL, SIMULATED, or TEST data:

    EXERCISE:&nbsp;Data pertaining to a government or military exercise. The data
    may include both real and simulated data.

    REAL:&nbsp;Data collected or produced that pertains to real-world objects,
    events, and analysis.

    SIMULATED:&nbsp;Synthetic data generated by a model to mimic real-world
    datasets.

    TEST:&nbsp;Specific datasets used to evaluate compliance with specifications and
    requirements, and for validating technical, functional, and performance
    characteristics.
    """

    end_time: datetime = FieldInfo(alias="endTime")
    """
    End time for OD solution in ISO 8601 UTC datetime format, with microsecond
    precision.
    """

    initial_od: bool = FieldInfo(alias="initialOD")
    """Flag indicating whether this is an initial orbit determination."""

    method: str
    """Orbit determination method used to produce this record (e.g.

    BLS, KF, UKF, etc.).
    """

    source: str
    """Source of the data."""

    start_time: datetime = FieldInfo(alias="startTime")
    """
    Start time for OD solution in ISO 8601 UTC datetime format, with microsecond
    precision.
    """

    id: Optional[str] = None
    """Unique identifier of the record, auto-generated by the system."""

    accepted_ob_ids: Optional[List[str]] = FieldInfo(alias="acceptedObIds", default=None)
    """Array of UDL data (observation) UUIDs that were accepted in this OD solution.

    See the associated acceptedObTyps array for the specific types of observations
    for the positionally corresponding UUIDs in this array (the two arrays must
    match in size).
    """

    accepted_ob_typs: Optional[List[str]] = FieldInfo(alias="acceptedObTyps", default=None)
    """Array of UDL observation types (e.g.

    DOA, EO, RADAR, RF) of the observations that were accepted in this OD solution.
    See the associated acceptedObIds array for the records UUID(s), positionally
    corresponding to the record types in this array. The acceptedObTyps and
    acceptedObIds arrays must match in size.
    """

    agom_est: Optional[bool] = FieldInfo(alias="agomEst", default=None)
    """Flag indicating whether the AGOM was estimated during this OD solution."""

    agom_model: Optional[str] = FieldInfo(alias="agomModel", default=None)
    """Model used to estimate the AGOM."""

    apriori_elset: Optional["Elset"] = FieldInfo(alias="aprioriElset", default=None)
    """
    An element set is a collection of Keplerian orbital elements describing an orbit
    of a particular satellite. The data is used along with an orbit propagator in
    order to predict the motion of a satellite. The element set, or elset for short,
    consists of identification data, the classical elements and drag parameters.
    """

    apriori_id_elset: Optional[str] = FieldInfo(alias="aprioriIdElset", default=None)
    """Identifier of the element set used to seed this OD solution.

    This ID can be used to obtain additional information on an Elset object using
    the 'get by ID' operation (e.g. /udl/elset/{id}). For example, the Elset with
    idElset = abc would be queried as /udl/elset/abc.
    """

    apriori_id_state_vector: Optional[str] = FieldInfo(alias="aprioriIdStateVector", default=None)
    """Identifier of the state vector used to seed this OD solution.

    This ID can be used to obtain additional information on a StateVector object
    using the 'get by ID' operation (e.g. /udl/statevector/{id}). For example, the
    StateVector with idStateVector = abc would be queried as /udl/statevector/abc.
    """

    apriori_state_vector: Optional["StateVectorFull"] = FieldInfo(alias="aprioriStateVector", default=None)
    """
    This service provides operations for querying and manipulation of state vectors
    for OnOrbit objects. State vectors are cartesian vectors of position (r) and
    velocity (v) that, together with their time (epoch) (t), uniquely determine the
    trajectory of the orbiting body in space. J2000 is the preferred coordinate
    frame for all state vector positions/velocities in UDL, but in some cases data
    may be in another frame depending on the provider and/or datatype. Please see
    the 'Discover' tab in the storefront to confirm coordinate frames by data
    provider.
    """

    ballistic_coeff_est: Optional[bool] = FieldInfo(alias="ballisticCoeffEst", default=None)
    """
    Flag indicating whether the ballistic coefficient was estimated during this OD
    solution.
    """

    ballistic_coeff_model: Optional[str] = FieldInfo(alias="ballisticCoeffModel", default=None)
    """Model used to estimate the ballistic coefficient."""

    best_pass_wrms: Optional[float] = FieldInfo(alias="bestPassWrms", default=None)
    """
    Lowest Weighted Root Mean Squared (RMS) value achieved for any single satellite
    pass during the observation span, indicating the pass with the highest quality
    OD solution.
    """

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Time the row was created in the database, auto-populated by the system."""

    created_by: Optional[str] = FieldInfo(alias="createdBy", default=None)
    """
    Application user who created the row in the database, auto-populated by the
    system.
    """

    edr: Optional[float] = None
    """Model parameter value for energy dissipation rate (EDR) in watts per kilogram."""

    effective_from: Optional[datetime] = FieldInfo(alias="effectiveFrom", default=None)
    """
    Optional start time at which this OD solution is accurate, in ISO 8601 UTC
    datetime format with microsecond precision.
    """

    effective_until: Optional[datetime] = FieldInfo(alias="effectiveUntil", default=None)
    """
    Optional end time at which this OD solution may no longer be accurate, in ISO
    8601 UTC datetime format with microsecond precision.
    """

    error_growth_rate: Optional[float] = FieldInfo(alias="errorGrowthRate", default=None)
    """Error growth rate of the OD solution in kilometers per day."""

    first_pass_wrms: Optional[float] = FieldInfo(alias="firstPassWrms", default=None)
    """
    The Weighted Root Mean Squared (RMS) calculated for the first satellite pass in
    the observation span. Serves as the initial quality metric for the beginning of
    the observation period.
    """

    fit_span: Optional[float] = FieldInfo(alias="fitSpan", default=None)
    """The fit span, in days, used in a Batch Least Squares (BLS) OD."""

    id_on_orbit: Optional[str] = FieldInfo(alias="idOnOrbit", default=None)
    """Unique identifier of the target satellite on-orbit object.

    This ID can be used to obtain additional information on an OnOrbit object using
    the 'get by ID' operation (e.g. /udl/onorbit/{id}). For example, the OnOrbit
    with idOnOrbit = 25544 would be queried as /udl/onorbit/25544.
    """

    last_ob_end: Optional[datetime] = FieldInfo(alias="lastObEnd", default=None)
    """
    The end of the time interval containing the time of the last accepted
    observation, in ISO 8601 UTC datetime format with microsecond precision. For an
    exact observation time, the lastObStart and lastObEnd are the same.
    """

    last_ob_start: Optional[datetime] = FieldInfo(alias="lastObStart", default=None)
    """
    The start of the time interval containing the time of the last accepted
    observation, in ISO 8601 UTC datetime format with microsecond precision. For an
    exact observation time, the lastObStart and lastObEnd are the same.
    """

    method_source: Optional[str] = FieldInfo(alias="methodSource", default=None)
    """Source of orbit determination method used to produce this record (e.g.

    ASW, ACTRAC, FreeFlyer, GEODYNE, GDTS, etc.).
    """

    num_iterations: Optional[int] = FieldInfo(alias="numIterations", default=None)
    """The number of iterations taken for the algorithm to converge on an OD solution."""

    on_orbit: Optional["Onorbit"] = FieldInfo(alias="onOrbit", default=None)
    """Model object representing on-orbit objects or satellites in the system."""

    origin: Optional[str] = None
    """
    Originating system or organization which produced the data, if different from
    the source. The origin may be different than the source if the source was a
    mediating system which forwarded the data on behalf of the origin system. If
    null, the source may be assumed to be the origin.
    """

    orig_network: Optional[str] = FieldInfo(alias="origNetwork", default=None)
    """
    The originating source network on which this record was created, auto-populated
    by the system.
    """

    orig_object_id: Optional[str] = FieldInfo(alias="origObjectId", default=None)
    """
    Optional identifier provided by the OD source to indicate the target on-orbit
    object of this OD solution. This may be an internal identifier and not
    necessarily map to a valid satellite number.
    """

    previous_wrms: Optional[float] = FieldInfo(alias="previousWrms", default=None)
    """
    The Weighted Root Mean Squared (RMS) of the differential correction from the
    previous overhead pass of the satellite. Provides a point of comparison for
    assessing changes in the quality of the OD solution between consecutive passes.
    """

    rejected_ob_ids: Optional[List[str]] = FieldInfo(alias="rejectedObIds", default=None)
    """Array of UDL data (observation) UUIDs that were rejected in this OD solution.

    See the associated rejectedObTyps array for the specific types of observations
    for the positionally corresponding UUIDs in this array (the two arrays must
    match in size).
    """

    rejected_ob_typs: Optional[List[str]] = FieldInfo(alias="rejectedObTyps", default=None)
    """Array of UDL observation types (e.g.

    DOA, EO, RADAR, RF) of the observations that were rejected in this OD solution.
    See the associated rejectedObIds array for the records UUID(s), positionally
    corresponding to the record types in this array. The rejectedObTyps and
    rejectedObIds arrays must match in size.
    """

    rms_convergence_criteria: Optional[float] = FieldInfo(alias="rmsConvergenceCriteria", default=None)
    """
    OD parameter value for the Root Mean Square (RMS) convergence criteria to
    successfully close the OD solution.
    """

    sat_no: Optional[int] = FieldInfo(alias="satNo", default=None)
    """Satellite/Catalog number of the target on-orbit object."""

    sensor_ids: Optional[List[str]] = FieldInfo(alias="sensorIds", default=None)
    """
    Array of UDL UUIDs (idSensor) of the sensors that contributed observations in
    this OD solution.
    """

    source_dl: Optional[str] = FieldInfo(alias="sourceDL", default=None)
    """The source data library from which this record was received.

    This could be a remote or tactical UDL or another data library. If null, the
    record should be assumed to have originated from the primary Enterprise UDL.
    """

    time_span: Optional[float] = FieldInfo(alias="timeSpan", default=None)
    """The time span used for the OD of the object, in days."""

    wrms: Optional[float] = None
    """
    The Weighted Root Mean Squared (RMS) of the differential correction of the
    target object that produced this OD state. WRMS is a quality indicator of the OD
    update, with a value of 1.00 being optimal. WRMS applies to batch least squares
    (BLS) processes.
    """


from ...elset import Elset
from ...shared.onorbit import Onorbit
from ...state_vector_full import StateVectorFull

if PYDANTIC_V2:
    OrbitdeterminationFull.model_rebuild()
else:
    OrbitdeterminationFull.update_forward_refs()  # type: ignore
