# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Optional
from datetime import datetime
from typing_extensions import Literal

from pydantic import Field as FieldInfo

from ..._models import BaseModel

__all__ = ["DiffofarrivalAbridged"]


class DiffofarrivalAbridged(BaseModel):
    """
    Model representation of Signal time and frequency difference of arrival (TDOA/FDOA) information obtained by using passive RF based sensor phenomenologies and sensor triangulation.
    """

    classification_marking: str = FieldInfo(alias="classificationMarking")
    """Classification marking of the data in IC/CAPCO Portion-marked format."""

    data_mode: Literal["REAL", "TEST", "SIMULATED", "EXERCISE"] = FieldInfo(alias="dataMode")
    """Indicator of whether the data is REAL, TEST, EXERCISE, or SIMULATED data:

    REAL: Data collected or produced that pertains to real-world objects, events,
    and analysis.

    TEST: Specific datasets used to evaluate compliance with specifications and
    requirements, and for validating technical, functional, and performance
    characteristics.

    EXERCISE: Data pertaining to a government or military exercise. The data may
    include both real and simulated data.

    SIMULATED: Synthetic data generated by a model to mimic real-world datasets.
    """

    ob_time: datetime = FieldInfo(alias="obTime")
    """Ob detection time in ISO 8601 UTC with microsecond precision."""

    source: str
    """Source of the data."""

    id: Optional[str] = None
    """Unique identifier of the record, auto-generated by the system."""

    azimuth1: Optional[float] = None
    """Line of sight azimuth angle for sensor 1, in degrees and topocentric frame.

    Azimuth ranges from 0 to 360 degrees.
    """

    azimuth2: Optional[float] = None
    """Line of sight azimuth angle for sensor 2, in degrees and topocentric frame.

    Azimuth ranges from 0 to 360 degrees.
    """

    bandwidth: Optional[float] = None
    """Bandwidth of the signal, in hertz."""

    collection_mode: Optional[str] = FieldInfo(alias="collectionMode", default=None)
    """
    Collection mode (e.g., DIRECTED_SEARCH, MANUAL, NEIGHBORHOOD_WATCH, SPOT_SEARCH,
    SURVEY, etc.).
    """

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Time the row was created in the database, auto-populated by the system."""

    created_by: Optional[str] = FieldInfo(alias="createdBy", default=None)
    """
    Application user who created the row in the database, auto-populated by the
    system.
    """

    delta_range: Optional[float] = FieldInfo(alias="deltaRange", default=None)
    """Delta range, in kilometers.

    Delta range calculation convention is (sensor2 - sensor1).
    """

    delta_range_rate: Optional[float] = FieldInfo(alias="deltaRangeRate", default=None)
    """Delta range rate, in kilometers per second.

    Delta range rate calculation convention is (sensor2 - sensor1).
    """

    delta_range_rate_unc: Optional[float] = FieldInfo(alias="deltaRangeRateUnc", default=None)
    """One sigma uncertainty in the delta range rate, in kilometers per second."""

    delta_range_unc: Optional[float] = FieldInfo(alias="deltaRangeUnc", default=None)
    """One sigma uncertainty in delta range, in kilometers."""

    descriptor: Optional[str] = None
    """Optional source-provided and searchable metadata or descriptor of the data."""

    elevation1: Optional[float] = None
    """Line of sight elevation angle for sensor 1, in degrees and topocentric frame.

    Elevation ranges from -90 to 90 degrees.
    """

    elevation2: Optional[float] = None
    """Line of sight elevation angle for sensor 2, in degrees and topocentric frame.

    Elevation ranges from -90 to 90 degrees.
    """

    fdoa: Optional[float] = None
    """Frequency difference of arrival of the center frequency signal, in hertz.

    FDOA calculation convention is (sensor2 - sensor1).
    """

    fdoa_unc: Optional[float] = FieldInfo(alias="fdoaUnc", default=None)
    """
    One sigma uncertainty in frequency difference of arrival of the center frequency
    signal, in hertz.
    """

    frequency: Optional[float] = None
    """Center frequency of the collect, in hertz."""

    id_on_orbit: Optional[str] = FieldInfo(alias="idOnOrbit", default=None)
    """Unique identifier of the target on-orbit object, if correlated."""

    id_sensor1: Optional[str] = FieldInfo(alias="idSensor1", default=None)
    """Sensor ID of the primary/1st sensor used for this measurement."""

    id_sensor2: Optional[str] = FieldInfo(alias="idSensor2", default=None)
    """Sensor ID of the secondary/2nd sensor used for this measurement."""

    origin: Optional[str] = None
    """
    Originating system or organization which produced the data, if different from
    the source. The origin may be different than the source if the source was a
    mediating system which forwarded the data on behalf of the origin system. If
    null, the source may be assumed to be the origin.
    """

    orig_network: Optional[str] = FieldInfo(alias="origNetwork", default=None)
    """
    The originating source network on which this record was created, auto-populated
    by the system.
    """

    orig_object_id: Optional[str] = FieldInfo(alias="origObjectId", default=None)
    """
    Optional identifier provided by observation source to indicate the target
    onorbit object of this observation. This may be an internal identifier and not
    necessarily a valid satellite number.
    """

    orig_sensor_id1: Optional[str] = FieldInfo(alias="origSensorId1", default=None)
    """
    Optional identifier provided by DOA source to indicate the primary/1st sensor
    identifier used for this measurement. This may be an internal identifier and not
    necessarily a valid sensor ID.
    """

    orig_sensor_id2: Optional[str] = FieldInfo(alias="origSensorId2", default=None)
    """
    Optional identifier provided by DOA source to indicate the secondary/2nd sensor
    identifier used for this this observation. This may be an internal identifier
    and not necessarily a valid sensor ID.
    """

    polarity_type: Optional[str] = FieldInfo(alias="polarityType", default=None)
    """Transponder polarization e.g.

    H - (Horizontally Polarized) Perpendicular to Earth's surface, V - (Vertically
    Polarized) Parallel to Earth's surface, L - (Left Hand Circularly Polarized)
    Rotating left relative to the earth's surface, R - (Right Hand Circularly
    Polarized) Rotating right relative to the earth's surface.
    """

    sat_no: Optional[int] = FieldInfo(alias="satNo", default=None)
    """Catalog number of the target on-orbit object."""

    sen2alt: Optional[float] = None
    """Sensor 2 altitude at obTime (if mobile/onorbit), in kilometers.

    If null, can be obtained from sensor info.
    """

    sen2lat: Optional[float] = None
    """Sensor 2 WGS84 latitude at obTime (if mobile/onorbit), in degrees.

    If null, can be obtained from sensor info. -90 to 90 degrees (negative values
    south of equator).
    """

    sen2lon: Optional[float] = None
    """Sensor 2 WGS84 longitude at obTime (if mobile/onorbit), in degrees.

    If null, can be obtained from sensor info. -180 to 180 degrees (negative values
    west of Prime Meridian).
    """

    senalt: Optional[float] = None
    """Sensor altitude at obTime (if mobile/onorbit), in kilometers.

    If null, can be obtained from sensor info.
    """

    senlat: Optional[float] = None
    """Sensor WGS84 latitude at obTime (if mobile/onorbit), in degrees.

    If null, can be obtained from sensor info. -90 to 90 degrees (negative values
    south of equator).
    """

    senlon: Optional[float] = None
    """Sensor WGS84 longitude at obTime (if mobile/onorbit), in degrees.

    If null, can be obtained from sensor info. -180 to 180 degrees (negative values
    west of Prime Meridian).
    """

    sensor1_delay: Optional[float] = FieldInfo(alias="sensor1Delay", default=None)
    """The signal arrival delay relative to sensor 1, in seconds."""

    sensor2_delay: Optional[float] = FieldInfo(alias="sensor2Delay", default=None)
    """The signal arrival delay relative to sensor 2, in seconds."""

    snr: Optional[float] = None
    """Signal to noise ratio, in decibels."""

    source_dl: Optional[str] = FieldInfo(alias="sourceDL", default=None)
    """The source data library from which this record was received.

    This could be a remote or tactical UDL or another data library. If null, the
    record should be assumed to have originated from the primary Enterprise UDL.
    """

    task_id: Optional[str] = FieldInfo(alias="taskId", default=None)
    """
    Optional identifier to indicate the specific tasking which produced this
    observation.
    """

    tdoa: Optional[float] = None
    """Time difference of arrival of the center frequency signal, in seconds.

    TDOA calculation convention is (sensor2 - sensor1).
    """

    tdoa_amb: Optional[int] = FieldInfo(alias="tdoaAmb", default=None)
    """
    The number of full signal cycles the time difference of arrival measurement
    could be shifted due to repeating patterns in the signal (0 = no ambiguity, +1 =
    one positive cycle ambiguity, -1 = one negative cycle ambiguity).
    """

    tdoa_unc: Optional[float] = FieldInfo(alias="tdoaUnc", default=None)
    """
    One sigma uncertainty in time difference of arrival of the center frequency
    signal, in seconds.
    """

    transaction_id: Optional[str] = FieldInfo(alias="transactionId", default=None)
    """
    Optional identifier to track a commercial or marketplace transaction executed to
    produce this data.
    """

    uct: Optional[bool] = None
    """
    Boolean indicating this observation is part of an uncorrelated track or was
    unable to be correlated to a known object. This flag should only be set to true
    by data providers after an attempt to correlate to an on-orbit object was made
    and failed. If unable to correlate, the 'origObjectId' field may be populated
    with an internal data provider specific identifier.
    """
