# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import List, Union, Iterable
from datetime import datetime
from typing_extensions import Literal, Required, Annotated, TypedDict

from .._utils import PropertyInfo

__all__ = ["AnalyticImageryCreateParams"]


class AnalyticImageryCreateParams(TypedDict, total=False):
    classification_marking: Required[Annotated[str, PropertyInfo(alias="classificationMarking")]]
    """Classification marking of the data in IC/CAPCO Portion-marked format."""

    content: Required[str]
    """
    General type of content of this image (CONTOUR, DIAGRAM, HEATMAP, HISTOGRAM,
    PLOT, SCREENSHOT).
    """

    data_mode: Required[Annotated[Literal["REAL", "TEST", "SIMULATED", "EXERCISE"], PropertyInfo(alias="dataMode")]]
    """Indicator of whether the data is REAL, TEST, SIMULATED, or EXERCISE data."""

    description: Required[str]
    """Description of the image content and utility."""

    filename: Required[str]
    """The image file name."""

    filesize: Required[int]
    """The image file size, in bytes.

    The maximum file size for this service is 40,000,000 bytes (40MB). Files
    exceeding the maximum size will be rejected.
    """

    image_type: Required[Annotated[str, PropertyInfo(alias="imageType")]]
    """The type of image associated with this record (GIF, JPG, PNG, TIF)."""

    msg_time: Required[Annotated[Union[str, datetime], PropertyInfo(alias="msgTime", format="iso8601")]]
    """
    The message time of this image record, in ISO8601 UTC format with millisecond
    precision.
    """

    source: Required[str]
    """Source of the data."""

    id: str
    """Unique identifier of the record, auto-generated by the system."""

    agjson: str
    """
    Geographical region or polygon (lat/lon pairs), as depicted by the GeoJSON
    representation of the geometry/geography, of the image as projected on the
    ground. GeoJSON Reference: https://geojson.org/. Ignored if included with a POST
    or PUT request that also specifies a valid 'area' or 'atext' field.
    """

    andims: int
    """Number of dimensions of the geometry depicted by region."""

    ann_lims: Annotated[Iterable[Iterable[int]], PropertyInfo(alias="annLims")]
    """
    Rectangular annotation limits, specified in pixels, as an array of arrays of the
    coordinates [ [UL1x, UL1y], [UR1x, UR1y], [LR1x, LR1y], [LL1x, LL1y] ],
    indicating the corners of a rectangle beginning with the Upper Left (UL) and
    moving clockwise. Allows the image provider to highlight one or more rectangular
    area(s) of interest. The array must contain Nx4 two-element arrays, where N is
    the number of rectangles of interest. The associated annotation(s) should be
    included in the annText array.
    """

    ann_text: Annotated[List[str], PropertyInfo(alias="annText")]
    """
    Annotation text, a string array of annotation(s) corresponding to the
    rectangular areas specified in annLims. This array contains the annotation text
    associated with the areas of interest indicated in annLims, in order. This array
    should contain one annotation per four values of the area (annLims) array.
    """

    area: str
    """
    Optional geographical region or polygon (lat/lon pairs) of the area surrounding
    the point of interest as projected on the ground.
    """

    asrid: int
    """Geographical spatial_ref_sys for region."""

    atext: str
    """
    Geographical region or polygon (lon/lat pairs), as depicted by the Well-Known
    Text representation of the geometry/geography, of the image as projected on the
    ground. WKT reference: https://www.opengeospatial.org/standards/wkt-crs. Ignored
    if included with a POST or PUT request that also specifies a valid 'area' field.
    """

    atype: str
    """Type of region as projected on the ground."""

    data_start: Annotated[Union[str, datetime], PropertyInfo(alias="dataStart", format="iso8601")]
    """
    The start time, in ISO8601 UTC format with millisecond precision, of the data
    used in the analysis or composition of the image content, when applicable.
    """

    data_stop: Annotated[Union[str, datetime], PropertyInfo(alias="dataStop", format="iso8601")]
    """
    The stop time, in ISO8601 UTC format with millisecond precision, of the data
    used in the analysis or composition of the image content, when applicable.
    """

    image_set_id: Annotated[str, PropertyInfo(alias="imageSetId")]
    """User-defined set ID of a sequence of images.

    Used to associate related analytic image records.
    """

    image_set_length: Annotated[int, PropertyInfo(alias="imageSetLength")]
    """The number of images in an image set."""

    img_height: Annotated[int, PropertyInfo(alias="imgHeight")]
    """The image height (vertical), in pixels."""

    img_width: Annotated[int, PropertyInfo(alias="imgWidth")]
    """The image width (horizontal), in pixels."""

    keywords: List[str]
    """Array of searchable keywords for this analytic imagery record."""

    origin: str
    """
    Originating system or organization which produced the data, if different from
    the source. The origin may be different than the source if the source was a
    mediating system which forwarded the data on behalf of the origin system. If
    null, the source may be assumed to be the origin.
    """

    sat_id: Annotated[List[str], PropertyInfo(alias="satId")]
    """Assessed satellite ID (NORAD RSO object number).

    The 'satId' and 'satIdConf' arrays must match in size.
    """

    sat_id_conf: Annotated[Iterable[float], PropertyInfo(alias="satIdConf")]
    """Assessed satellite confidence corresponding to an assessment ID.

    Values are between 0.0 and 1.0. The 'satId' and 'satIdConf' arrays must match in
    size.
    """

    sequence_id: Annotated[int, PropertyInfo(alias="sequenceId")]
    """The sequence number of an image within an image set.

    If null, then it is assumed that the order of images in an imageSet is not
    relevant.
    """

    src_ids: Annotated[List[str], PropertyInfo(alias="srcIds")]
    """Array of UUIDs of the UDL data records that are related to this image.

    See the associated 'srcTyps' array for the specific types of data, positionally
    corresponding to the UUIDs in this array. The 'srcTyps' and 'srcIds' arrays must
    match in size. See the corresponding srcTyps array element for the data type of
    the UUID and use the appropriate API operation to retrieve that object.
    """

    src_typs: Annotated[List[str], PropertyInfo(alias="srcTyps")]
    """
    Array of UDL record types (AIS, CONJUNCTION, DOA, ELSET, EO, ESID, GROUNDIMAGE,
    POI, MANEUVER, MTI, NOTIFICATION, RADAR, RF, SIGACT, SKYIMAGE, SV, TRACK) that
    are related to this image. See the associated 'srcIds' array for the record
    UUIDs, positionally corresponding to the record types in this array. The
    'srcTyps' and 'srcIds' arrays must match in size.
    """

    tags: List[str]
    """
    Optional array of provider/source specific tags for this data, where each
    element is no longer than 32 characters, used for implementing data owner
    conditional access controls to restrict access to the data. Should be left null
    by data providers unless conditional access controls are coordinated with the
    UDL team.
    """

    transaction_id: Annotated[str, PropertyInfo(alias="transactionId")]
    """
    Optional identifier to track a commercial or marketplace transaction executed to
    produce this data.
    """

    x_units: Annotated[str, PropertyInfo(alias="xUnits")]
    """
    Optional field indicating the units that apply to the x-axis of the attached
    image, when applicable.
    """

    y_units: Annotated[str, PropertyInfo(alias="yUnits")]
    """
    Optional field indicating the units that apply to the y-axis of the attached
    image, when applicable.
    """

    z_units: Annotated[str, PropertyInfo(alias="zUnits")]
    """
    Optional field indicating the units that apply to the z-axis of the attached
    image, when applicable.
    """
