# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import List, Union, Iterable
from datetime import datetime
from typing_extensions import Literal, Required, Annotated, TypedDict

from .._utils import PropertyInfo
from .state_vector_ingest_param import StateVectorIngestParam

__all__ = ["ConjunctionCreateBulkParams", "Body"]


class ConjunctionCreateBulkParams(TypedDict, total=False):
    body: Required[Iterable[Body]]


class Body(TypedDict, total=False):
    classification_marking: Required[Annotated[str, PropertyInfo(alias="classificationMarking")]]
    """Classification marking of the data in IC/CAPCO Portion-marked format."""

    data_mode: Required[Annotated[Literal["REAL", "TEST", "SIMULATED", "EXERCISE"], PropertyInfo(alias="dataMode")]]
    """Indicator of whether the data is EXERCISE, REAL, SIMULATED, or TEST data:

    EXERCISE:&nbsp;Data pertaining to a government or military exercise. The data
    may include both real and simulated data.

    REAL:&nbsp;Data collected or produced that pertains to real-world objects,
    events, and analysis.

    SIMULATED:&nbsp;Synthetic data generated by a model to mimic real-world
    datasets.

    TEST:&nbsp;Specific datasets used to evaluate compliance with specifications and
    requirements, and for validating technical, functional, and performance
    characteristics.
    """

    source: Required[str]
    """Source of the data."""

    tca: Required[Annotated[Union[str, datetime], PropertyInfo(format="iso8601")]]
    """Time of closest approach (TCA) in UTC."""

    id: str
    """Unique identifier of the record, auto-generated by the system."""

    ccir: str
    """Commander's critical information requirements notes."""

    cd_ao_m1: Annotated[float, PropertyInfo(alias="cdAoM1")]
    """
    The value of the primary (object1) Area times the drag coefficient over the
    object Mass, expressed in m^2/kg, used for propagation of the primary state
    vector and covariance to TCA.
    """

    cd_ao_m2: Annotated[float, PropertyInfo(alias="cdAoM2")]
    """
    The value of the secondary (object2) Area times the drag coefficient over the
    object Mass, expressed in m^2/kg, used for propagation of the primary state
    vector and covariance to TCA.
    """

    collision_prob: Annotated[float, PropertyInfo(alias="collisionProb")]
    """
    Probability of Collision is the probability (denoted p, where 0.0<=p<=1.0), that
    Object1 and Object2 will collide.
    """

    collision_prob_method: Annotated[str, PropertyInfo(alias="collisionProbMethod")]
    """The method that was used to calculate the collision probability, ex.

    FOSTER-1992.
    """

    comments: str
    """Additional notes from data providers."""

    concern_notes: Annotated[str, PropertyInfo(alias="concernNotes")]
    """Emergency comments."""

    cr_ao_m1: Annotated[float, PropertyInfo(alias="crAoM1")]
    """
    The value of the primary (object1) Area times the solar radiation pressure
    coefficient over the object Mass, expressed in m^2/kg, used for propagation of
    the primary state vector and covariance to TCA. This parameter is sometimes
    referred to as AGOM.
    """

    cr_ao_m2: Annotated[float, PropertyInfo(alias="crAoM2")]
    """
    The value of the secondary (object2) Area times the solar radiation pressure
    coefficient over the object Mass, expressed in m^2/kg, used for propagation of
    the primary state vector and covariance to TCA. This parameter is sometimes
    referred to as AGOM.
    """

    descriptor: str
    """Optional source-provided and searchable metadata or descriptor of the data."""

    ephem_name1: Annotated[str, PropertyInfo(alias="ephemName1")]
    """
    The filename of the primary (object1) ephemeris used in the screening, if
    applicable.
    """

    ephem_name2: Annotated[str, PropertyInfo(alias="ephemName2")]
    """
    The filename of the secondary (object2) ephemeris used in the screening, if
    applicable.
    """

    es_id1: Annotated[str, PropertyInfo(alias="esId1")]
    """
    Unique identifier of the parent Ephemeris Set of the primary (object1) ephemeris
    used in the screening, if applicable.
    """

    es_id2: Annotated[str, PropertyInfo(alias="esId2")]
    """
    Unique identifier of the parent Ephemeris Set of the secondary (object2)
    ephemeris used in the screening, if applicable.
    """

    event_id: Annotated[str, PropertyInfo(alias="eventId")]
    """Optional source-provided identifier for this conjunction event.

    In the case where multiple conjunction records are submitted for the same event,
    this field can be used to tie them together to the same event.
    """

    id_state_vector1: Annotated[str, PropertyInfo(alias="idStateVector1")]
    """Optional ID of the UDL State Vector at TCA of the primary object.

    When performing a create, this id will be ignored in favor of the UDL generated
    id of the stateVector1.
    """

    id_state_vector2: Annotated[str, PropertyInfo(alias="idStateVector2")]
    """Optional ID of the UDL State Vector at TCA of the secondary object.

    When performing a create, this id will be ignored in favor of the UDL generated
    id of the stateVector2.
    """

    large_cov_warning: Annotated[bool, PropertyInfo(alias="largeCovWarning")]
    """
    Used for probability of collision calculation, not Warning/Alert Threshold
    notifications.
    """

    large_rel_pos_warning: Annotated[bool, PropertyInfo(alias="largeRelPosWarning")]
    """
    Used for probability of collision calculation, not Warning/Alert Threshold
    notifications.
    """

    last_ob_time1: Annotated[Union[str, datetime], PropertyInfo(alias="lastObTime1", format="iso8601")]
    """Time of last positive metric observation of the primary satellite."""

    last_ob_time2: Annotated[Union[str, datetime], PropertyInfo(alias="lastObTime2", format="iso8601")]
    """Time of last positive metric observation of the secondary satellite."""

    message_for: Annotated[str, PropertyInfo(alias="messageFor")]
    """Spacecraft name(s) for which the Collision message is provided."""

    message_id: Annotated[str, PropertyInfo(alias="messageId")]
    """JMS provided message ID link."""

    miss_distance: Annotated[float, PropertyInfo(alias="missDistance")]
    """Distance between objects at Time of Closest Approach (TCA) in meters."""

    orig_id_on_orbit1: Annotated[str, PropertyInfo(alias="origIdOnOrbit1")]
    """Optional place holder for an OnOrbit ID that does not exist in UDL."""

    orig_id_on_orbit2: Annotated[str, PropertyInfo(alias="origIdOnOrbit2")]
    """Optional place holder for an OnOrbit ID that does not exist in UDL."""

    origin: str
    """
    Originating system or organization which produced the data, if different from
    the source. The origin may be different than the source if the source was a
    mediating system which forwarded the data on behalf of the origin system. If
    null, the source may be assumed to be the origin.
    """

    originator: str
    """
    Creating agency or owner/operator (may be different than provider who submitted
    the conjunction message).
    """

    owner_contacted: Annotated[bool, PropertyInfo(alias="ownerContacted")]
    """Flag indicating if owner was contacted."""

    penetration_level_sigma: Annotated[float, PropertyInfo(alias="penetrationLevelSigma")]
    """Penetration Level Sigma."""

    raw_file_uri: Annotated[str, PropertyInfo(alias="rawFileURI")]
    """Link to filename associated with JMS record."""

    rel_pos_n: Annotated[float, PropertyInfo(alias="relPosN")]
    """Distance between objects along Normal vector in meters."""

    rel_pos_r: Annotated[float, PropertyInfo(alias="relPosR")]
    """
    Distance between objects along Radial Vector at Time of Closest Approach in
    meters.
    """

    rel_pos_t: Annotated[float, PropertyInfo(alias="relPosT")]
    """Distance between objects along Tangential Vector in meters."""

    rel_vel_mag: Annotated[float, PropertyInfo(alias="relVelMag")]
    """
    Closing velocity magnitude (relative speed) at Time of Closest Approach in
    meters/sec.
    """

    rel_vel_n: Annotated[float, PropertyInfo(alias="relVelN")]
    """Closing velocity between objects along Normal Vector in meters/sec."""

    rel_vel_r: Annotated[float, PropertyInfo(alias="relVelR")]
    """
    Closing velocity between objects along Radial Vector at Time of Closest Approach
    in meters/sec.
    """

    rel_vel_t: Annotated[float, PropertyInfo(alias="relVelT")]
    """Closing velocity between objects along Tangential Vector in meters/sec."""

    sat_no1: Annotated[int, PropertyInfo(alias="satNo1")]
    """Satellite/catalog number of the target on-orbit primary object."""

    sat_no2: Annotated[int, PropertyInfo(alias="satNo2")]
    """Satellite/catalog number of the target on-orbit secondary object."""

    screen_entry_time: Annotated[Union[str, datetime], PropertyInfo(alias="screenEntryTime", format="iso8601")]
    """The start time in UTC of the screening period for the conjunction assessment."""

    screen_exit_time: Annotated[Union[str, datetime], PropertyInfo(alias="screenExitTime", format="iso8601")]
    """The stop time in UTC of the screening period for the conjunction assessment."""

    screen_volume_x: Annotated[float, PropertyInfo(alias="screenVolumeX")]
    """
    Component size of screen in X component of RTN (Radial, Transverse and Normal)
    frame in meters.
    """

    screen_volume_y: Annotated[float, PropertyInfo(alias="screenVolumeY")]
    """
    Component size of screen in Y component of RTN (Radial, Transverse and Normal)
    frame in meters.
    """

    screen_volume_z: Annotated[float, PropertyInfo(alias="screenVolumeZ")]
    """
    Component size of screen in Z component of RTN (Radial, Transverse and Normal)
    frame in meters.
    """

    small_cov_warning: Annotated[bool, PropertyInfo(alias="smallCovWarning")]
    """
    Used for probability of collision calculation, not Warning/Alert Threshold
    notifications.
    """

    small_rel_vel_warning: Annotated[bool, PropertyInfo(alias="smallRelVelWarning")]
    """
    Used for probability of collision calculation, not Warning/Alert Threshold
    notifications.
    """

    state_dept_notified: Annotated[bool, PropertyInfo(alias="stateDeptNotified")]
    """Flag indicating if State department was notified."""

    state_vector1: Annotated[StateVectorIngestParam, PropertyInfo(alias="stateVector1")]
    """
    This service provides operations for querying and manipulation of state vectors
    for OnOrbit objects. State vectors are cartesian vectors of position (r) and
    velocity (v) that, together with their time (epoch) (t), uniquely determine the
    trajectory of the orbiting body in space. J2000 is the preferred coordinate
    frame for all state vector positions/velocities in UDL, but in some cases data
    may be in another frame depending on the provider and/or datatype. Please see
    the 'Discover' tab in the storefront to confirm coordinate frames by data
    provider.
    """

    state_vector2: Annotated[StateVectorIngestParam, PropertyInfo(alias="stateVector2")]
    """
    This service provides operations for querying and manipulation of state vectors
    for OnOrbit objects. State vectors are cartesian vectors of position (r) and
    velocity (v) that, together with their time (epoch) (t), uniquely determine the
    trajectory of the orbiting body in space. J2000 is the preferred coordinate
    frame for all state vector positions/velocities in UDL, but in some cases data
    may be in another frame depending on the provider and/or datatype. Please see
    the 'Discover' tab in the storefront to confirm coordinate frames by data
    provider.
    """

    tags: List[str]
    """
    Optional array of provider/source specific tags for this data, where each
    element is no longer than 32 characters, used for implementing data owner
    conditional access controls to restrict access to the data. Should be left null
    by data providers unless conditional access controls are coordinated with the
    UDL team.
    """

    thrust_accel1: Annotated[float, PropertyInfo(alias="thrustAccel1")]
    """
    The primary (object1) acceleration, expressed in m/s^2, due to in-track thrust
    used to propagate the primary state vector and covariance to TCA.
    """

    thrust_accel2: Annotated[float, PropertyInfo(alias="thrustAccel2")]
    """
    The secondary (object2) acceleration, expressed in m/s^2, due to in-track thrust
    used to propagate the primary state vector and covariance to TCA.
    """

    transaction_id: Annotated[str, PropertyInfo(alias="transactionId")]
    """
    Optional identifier to track a commercial or marketplace transaction executed to
    produce this data.
    """

    type: str
    """The type of data represented in this conjunction record (e.g.

    CONJUNCTION, CARA-WORKLIST, etc.). If type is null the record is assumed to be a
    Conjunction.
    """

    uvw_warn: Annotated[bool, PropertyInfo(alias="uvwWarn")]
    """
    Used for probability of collision calculation, not Warning/Alert Threshold
    notifications.
    """

    vol_entry_time: Annotated[Union[str, datetime], PropertyInfo(alias="volEntryTime", format="iso8601")]
    """
    The time at which the secondary (object2) enters the screening volume, in ISO
    8601 UTC format with microsecond precision.
    """

    vol_exit_time: Annotated[Union[str, datetime], PropertyInfo(alias="volExitTime", format="iso8601")]
    """
    The time at which the secondary (object2) exits the screening volume, in ISO
    8601 UTC format with microsecond precision.
    """

    vol_shape: Annotated[str, PropertyInfo(alias="volShape")]
    """The shape (BOX, ELLIPSOID) of the screening volume."""
