# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional
from datetime import datetime
from typing_extensions import Literal

from pydantic import Field as FieldInfo

from .._models import BaseModel

__all__ = ["CrewAbridged", "CrewMember"]


class CrewMember(BaseModel):
    branch: Optional[str] = None
    """The military branch assignment of the crew member."""

    civilian: Optional[bool] = None
    """Flag indicating this crew member is a civilian or non-military person."""

    commander: Optional[bool] = None
    """Flag indicating this person is the aircraft commander."""

    crew_position: Optional[str] = FieldInfo(alias="crewPosition", default=None)
    """The crew position of the crew member."""

    dod_id: Optional[str] = FieldInfo(alias="dodID", default=None)
    """The crew member's 10-digit DoD ID number."""

    duty_position: Optional[str] = FieldInfo(alias="dutyPosition", default=None)
    """The duty position of the crew member."""

    first_name: Optional[str] = FieldInfo(alias="firstName", default=None)
    """The first name of the crew member."""

    last4_ssn: Optional[str] = FieldInfo(alias="last4SSN", default=None)
    """Last four digits of the crew member's social security number."""

    last_name: Optional[str] = FieldInfo(alias="lastName", default=None)
    """The last name of the crew member."""

    member_id: Optional[str] = FieldInfo(alias="memberId", default=None)
    """Unique identifier of the crew member assigned by the originating source."""

    member_remarks: Optional[str] = FieldInfo(alias="memberRemarks", default=None)
    """Remarks concerning the crew member."""

    member_type: Optional[str] = FieldInfo(alias="memberType", default=None)
    """Amplifying details about the crew member type (e.g.

    RAVEN, FCC, COMCAM, AIRCREW, MEP, OTHER, etc.).
    """

    middle_initial: Optional[str] = FieldInfo(alias="middleInitial", default=None)
    """The middle initial of the crew member."""

    rank: Optional[str] = None
    """The rank of the crew member."""

    squadron: Optional[str] = None
    """The squadron the crew member serves."""

    username: Optional[str] = None
    """The Mattermost username of this crew member."""

    wing: Optional[str] = None
    """The wing the crew member serves."""


class CrewAbridged(BaseModel):
    classification_marking: str = FieldInfo(alias="classificationMarking")
    """Classification marking of the data in IC/CAPCO Portion-marked format."""

    data_mode: Literal["REAL", "TEST", "SIMULATED", "EXERCISE"] = FieldInfo(alias="dataMode")
    """Indicator of whether the data is EXERCISE, REAL, SIMULATED, or TEST data:

    EXERCISE:&nbsp;Data pertaining to a government or military exercise. The data
    may include both real and simulated data.

    REAL:&nbsp;Data collected or produced that pertains to real-world objects,
    events, and analysis.

    SIMULATED:&nbsp;Synthetic data generated by a model to mimic real-world
    datasets.

    TEST:&nbsp;Specific datasets used to evaluate compliance with specifications and
    requirements, and for validating technical, functional, and performance
    characteristics.
    """

    orig_crew_id: str = FieldInfo(alias="origCrewId")
    """Unique identifier of the formed crew provided by the originating source.

    Provided for systems that require tracking of an internal system generated ID.
    """

    source: str
    """Source of the data."""

    id: Optional[str] = None
    """Unique identifier of the record, auto-generated by the system."""

    adj_return_time: Optional[datetime] = FieldInfo(alias="adjReturnTime", default=None)
    """Adjusted return time in ISO 8601 UTC format with millisecond precision."""

    adj_return_time_approver: Optional[str] = FieldInfo(alias="adjReturnTimeApprover", default=None)
    """Last name of the adjusted return time approver."""

    aircraft_mds: Optional[str] = FieldInfo(alias="aircraftMDS", default=None)
    """The aircraft Model Design Series designation assigned for this crew."""

    alerted_time: Optional[datetime] = FieldInfo(alias="alertedTime", default=None)
    """Time the crew was alerted, in ISO8601 UTC format, with millisecond precision."""

    arms_crew_unit: Optional[str] = FieldInfo(alias="armsCrewUnit", default=None)
    """The crew's Aviation Resource Management System (ARMS) unit.

    If multiple units exist, use the Aircraft Commander's Unit.
    """

    arr_icao: Optional[str] = FieldInfo(alias="arrICAO", default=None)
    """Arrival location for the itinerary point.

    Intended to be an ICAO, but an air refueling track short name or drop zone ID
    can be used.
    """

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Time the row was created in the database, auto-populated by the system."""

    created_by: Optional[str] = FieldInfo(alias="createdBy", default=None)
    """
    Application user who created the row in the database, auto-populated by the
    system.
    """

    crew_home: Optional[bool] = FieldInfo(alias="crewHome", default=None)
    """
    Flag indicating whether this crew task takes the crew home and out of the stage.
    """

    crew_members: Optional[List[CrewMember]] = FieldInfo(alias="crewMembers", default=None)
    """CrewMembers Collection."""

    crew_name: Optional[str] = FieldInfo(alias="crewName", default=None)
    """Name of the formed crew."""

    crew_squadron: Optional[str] = FieldInfo(alias="crewSquadron", default=None)
    """The squadron the crew serves."""

    crew_type: Optional[str] = FieldInfo(alias="crewType", default=None)
    """Crew type."""

    crew_wing: Optional[str] = FieldInfo(alias="crewWing", default=None)
    """The wing the crew serves."""

    current_icao: Optional[str] = FieldInfo(alias="currentICAO", default=None)
    """
    The International Civil Aviation Organization (ICAO) code of the airfield at
    which the crew is currently located.
    """

    dep_icao: Optional[str] = FieldInfo(alias="depICAO", default=None)
    """Departure location for the itinerary point.

    Intended to be an ICAO, but an air refueling track short name or drop zone ID
    can be used.
    """

    est_arr_time: Optional[datetime] = FieldInfo(alias="estArrTime", default=None)
    """
    The estimated time of arrival at the arrival site (arrICAO) for the crew in ISO
    8601 UTC format with millisecond precision.
    """

    est_dep_time: Optional[datetime] = FieldInfo(alias="estDepTime", default=None)
    """
    The estimated time of departure for the crew in ISO 8601 UTC format with
    millisecond precision.
    """

    fdp_elig_type: Optional[str] = FieldInfo(alias="fdpEligType", default=None)
    """Crew Flight Duty Period (FDP) eligibility type."""

    fdp_type: Optional[str] = FieldInfo(alias="fdpType", default=None)
    """Flight Duty Period (FDP) type."""

    female_enlisted_qty: Optional[int] = FieldInfo(alias="femaleEnlistedQty", default=None)
    """The number of female enlisted crew members."""

    female_officer_qty: Optional[int] = FieldInfo(alias="femaleOfficerQty", default=None)
    """The number of female officer crew members."""

    id_sortie: Optional[str] = FieldInfo(alias="idSortie", default=None)
    """Unique identifier of the Aircraft Sortie associated with this crew record."""

    init_start_time: Optional[datetime] = FieldInfo(alias="initStartTime", default=None)
    """Initial start time of the linked task that was delinked due to mission closure."""

    legal_alert_time: Optional[datetime] = FieldInfo(alias="legalAlertTime", default=None)
    """
    Time the crew is legal for alert, in ISO8601 UTC format, with millisecond
    precision.
    """

    legal_bravo_time: Optional[datetime] = FieldInfo(alias="legalBravoTime", default=None)
    """
    Time the crew is legal for bravo, in ISO8601 UTC format, with millisecond
    precision.
    """

    linked_task: Optional[bool] = FieldInfo(alias="linkedTask", default=None)
    """Flag indicating whether this crew is part of a linked flying task."""

    male_enlisted_qty: Optional[int] = FieldInfo(alias="maleEnlistedQty", default=None)
    """The number of male enlisted crew members."""

    male_officer_qty: Optional[int] = FieldInfo(alias="maleOfficerQty", default=None)
    """The number of male officer crew members."""

    mission_id: Optional[str] = FieldInfo(alias="missionId", default=None)
    """The mission ID the crew is supporting according to the source system."""

    origin: Optional[str] = None
    """
    Originating system or organization which produced the data, if different from
    the source. The origin may be different than the source if the source was a
    mediating system which forwarded the data on behalf of the origin system. If
    null, the source may be assumed to be the origin.
    """

    orig_network: Optional[str] = FieldInfo(alias="origNetwork", default=None)
    """
    The originating source network on which this record was created, auto-populated
    by the system.
    """

    post_rest_applied: Optional[bool] = FieldInfo(alias="postRestApplied", default=None)
    """
    Flag indicating whether post-mission crew rest is applied to the last sortie of
    a crew's task.
    """

    pre_rest_applied: Optional[bool] = FieldInfo(alias="preRestApplied", default=None)
    """
    Flag indicating whether pre-mission crew rest is applied to the first sortie of
    a crew's task.
    """

    return_time: Optional[datetime] = FieldInfo(alias="returnTime", default=None)
    """Scheduled return time, in ISO8601 UTC format, with millisecond precision."""

    stage_time: Optional[datetime] = FieldInfo(alias="stageTime", default=None)
    """
    Time the crew entered the stage in ISO 8601 UTC format with millisecond
    precision.
    """

    status: Optional[str] = None
    """Crew status (e.g.

    NEEDCREW, ASSIGNED, APPROVED, NOTIFIED, PARTIAL, UNKNOWN, etc.).
    """

    updated_at: Optional[datetime] = FieldInfo(alias="updatedAt", default=None)
    """Time the row was created in the database, auto-populated by the system."""

    updated_by: Optional[str] = FieldInfo(alias="updatedBy", default=None)
    """
    Application user who created the row in the database, auto-populated by the
    system.
    """
