# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import List, Union
from datetime import datetime
from typing_extensions import Literal, Required, Annotated, TypedDict

from .._utils import PropertyInfo

__all__ = ["RfgeolocationCreateParams"]


class RfgeolocationCreateParams(TypedDict, total=False):
    classification_marking: Required[Annotated[str, PropertyInfo(alias="classificationMarking")]]
    """Classification marking of the data in IC/CAPCO Portion-marked format."""

    data_mode: Required[Annotated[Literal["REAL", "TEST", "SIMULATED", "EXERCISE"], PropertyInfo(alias="dataMode")]]
    """Indicator of whether the data is EXERCISE, REAL, SIMULATED, or TEST data:

    EXERCISE:&nbsp;Data pertaining to a government or military exercise. The data
    may include both real and simulated data.

    REAL:&nbsp;Data collected or produced that pertains to real-world objects,
    events, and analysis.

    SIMULATED:&nbsp;Synthetic data generated by a model to mimic real-world
    datasets.

    TEST:&nbsp;Specific datasets used to evaluate compliance with specifications and
    requirements, and for validating technical, functional, and performance
    characteristics.
    """

    order_id: Required[Annotated[str, PropertyInfo(alias="orderId")]]
    """The order identifier for this RF Geo Location data set."""

    received_ts: Required[Annotated[Union[str, datetime], PropertyInfo(alias="receivedTs", format="iso8601")]]
    """
    The time representing the mean of the constituent single-burst observations in
    ISO 8601 UTC with microsecond precision.
    """

    source: Required[str]
    """Source of the data."""

    start_time: Required[Annotated[Union[str, datetime], PropertyInfo(alias="startTime", format="iso8601")]]
    """
    The order start time for this RF Geo Location data set in ISO 8601 UTC with
    microsecond precision.
    """

    id: str
    """Unique identifier of the record, auto-generated by the system."""

    agjson: str
    """
    Geographical region or polygon (lat/lon pairs), as depicted by the GeoJSON
    representation of the geometry/geography, of the image as projected on the
    ground. GeoJSON Reference: https://geojson.org/. Ignored if included with a POST
    or PUT request that also specifies a valid 'area' or 'atext' field.
    """

    alg_version: Annotated[str, PropertyInfo(alias="algVersion")]
    """The RFGeo algorithm type and version used in geolocation calculations."""

    andims: int
    """Number of dimensions of the geometry depicted by region."""

    area: str
    """
    Optional geographical region or polygon (lat/lon pairs) of the area surrounding
    the Point of Interest as projected on the ground.
    """

    asrid: int
    """Geographical spatial_ref_sys for region."""

    atext: str
    """
    Geographical region or polygon (lon/lat pairs), as depicted by the Well-Known
    Text representation of the geometry/geography, of the image as projected on the
    ground. WKT reference: https://www.opengeospatial.org/standards/wkt-crs. Ignored
    if included with a POST or PUT request that also specifies a valid 'area' field.
    """

    atype: str
    """Type of region as projected on the ground."""

    center_freq: Annotated[float, PropertyInfo(alias="centerFreq")]
    """The detected signal frequency in megahertz."""

    conf_area: Annotated[float, PropertyInfo(alias="confArea")]
    """
    The area of the confidence ellipse specified in meters squared to contain the
    emitter with a 95% probability.
    """

    conf_orientation: Annotated[float, PropertyInfo(alias="confOrientation")]
    """
    Confidence ellipse orientation of semi-major axis about the detection location
    lat/lon point measured in degrees.
    """

    conf_semi_major: Annotated[float, PropertyInfo(alias="confSemiMajor")]
    """
    Confidence ellipse semi-major axis about the detection location lat/lon point
    measured in meters.
    """

    conf_semi_minor: Annotated[float, PropertyInfo(alias="confSemiMinor")]
    """
    Confidence ellipse semi-minor axis about the detection location lat/lon point
    measured in meters.
    """

    constellation: str
    """The name of the satellite constellation."""

    created_ts: Annotated[Union[str, datetime], PropertyInfo(alias="createdTs", format="iso8601")]
    """
    Specifies the creation time associated with the order in ISO 8601 UTC with
    microsecond precision.
    """

    detect_alt: Annotated[float, PropertyInfo(alias="detectAlt")]
    """The altitude relative to WGS-84 ellipsoid, in meters."""

    detect_lat: Annotated[float, PropertyInfo(alias="detectLat")]
    """WGS-84 latitude of the most likely emitter location coordinate point, in
    degrees.

    -90 to 90 degrees (negative values south of equator).
    """

    detect_lon: Annotated[float, PropertyInfo(alias="detectLon")]
    """
    WGS-84 longitude of the most likely emitter location coordinate point, in
    degrees. -180 to 180 degrees (negative values west of Prime Meridian).
    """

    end_time: Annotated[Union[str, datetime], PropertyInfo(alias="endTime", format="iso8601")]
    """
    The order end time for this RF Geo Location data set in ISO 8601 UTC with
    microsecond precision.
    """

    external_id: Annotated[str, PropertyInfo(alias="externalId")]
    """Optional ID from external systems.

    This field has no meaning within UDL and is provided as a convenience for
    systems that require tracking of an internal system generated ID.
    """

    id_rf_emitter: Annotated[str, PropertyInfo(alias="idRFEmitter")]
    """
    Optional identifier of the geolocated signal of interest RF Emitter for this
    observation. This ID can be used to obtain additional information on an RF
    Emitter object using the 'get by ID' operation (e.g. /udl/rfemitter/{id}). For
    example, the rfemitter object with idRFEmitter = abc would be queried as
    /udl/rfemitter/abc.
    """

    max_freq: Annotated[float, PropertyInfo(alias="maxFreq")]
    """The maximum detected frequency in megahertz."""

    min_freq: Annotated[float, PropertyInfo(alias="minFreq")]
    """The minimum detected frequency in megahertz."""

    num_bursts: Annotated[int, PropertyInfo(alias="numBursts")]
    """The count of single-burst observations used for this geolocation observation."""

    origin: str
    """
    Originating system or organization which produced the data, if different from
    the source. The origin may be different than the source if the source was a
    mediating system which forwarded the data on behalf of the origin system. If
    null, the source may be assumed to be the origin.
    """

    orig_object_id: Annotated[str, PropertyInfo(alias="origObjectId")]
    """
    Optional identifier of the satellite used to identify and geolocate RF signals
    of interest of this observation. This may be an internal identifier and not
    necessarily a valid satellite number.
    """

    orig_rf_emitter_id: Annotated[str, PropertyInfo(alias="origRFEmitterId")]
    """Optional identifier of the emitter of interest for this observation.

    This may be an internal identifier and not necessarily a valid emitter Id.
    """

    pass_group_id: Annotated[str, PropertyInfo(alias="passGroupId")]
    """
    Optional external identifier referencing the entity used in the calculation of
    the geolocation.
    """

    sat_no: Annotated[int, PropertyInfo(alias="satNo")]
    """Satellite/catalog number of the target on-orbit object."""

    signal_of_interest: Annotated[str, PropertyInfo(alias="signalOfInterest")]
    """The name of the signal of interest."""

    tags: List[str]
    """
    Optional array of provider/source specific tags for this data, where each
    element is no longer than 32 characters, used for implementing data owner
    conditional access controls to restrict access to the data. Should be left null
    by data providers unless conditional access controls are coordinated with the
    UDL team.
    """
