# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing_extensions import Literal, Required, Annotated, TypedDict

from .._utils import PropertyInfo

__all__ = ["StarCatalogCreateParams"]


class StarCatalogCreateParams(TypedDict, total=False):
    astrometry_origin: Required[Annotated[str, PropertyInfo(alias="astrometryOrigin")]]
    """
    Originating astrometric catalog for this object (GA (GAIA), HI (HIPPARCOS), UB
    (USNOBSC), AL, AP, CA, CR, DU, FK6_I, FK6_III, PS, SK, TD, TP, TX, UC, UL, UH,
    UP, VH, VS, WD).
    """

    classification_marking: Required[Annotated[str, PropertyInfo(alias="classificationMarking")]]
    """Classification marking of the data in IC/CAPCO Portion-marked format."""

    cs_id: Required[Annotated[int, PropertyInfo(alias="csId")]]
    """The ID of this object in the specific catalog associated with this record.

    This field will either contain the value in the gncCatId or sdaCatId field.
    """

    data_mode: Required[Annotated[Literal["REAL", "TEST", "EXERCISE", "SIMULATED"], PropertyInfo(alias="dataMode")]]
    """Indicator of whether the data is REAL, TEST, EXERCISE, or SIMULATED data:

    REAL: Data collected or produced that pertains to real-world objects, events,
    and analysis.

    TEST: Specific datasets used to evaluate compliance with specifications and
    requirements, and for validating technical, functional, and performance
    characteristics.

    EXERCISE: Data pertaining to a government or military exercise. The data may
    include both real and simulated data.

    SIMULATED: Synthetic data generated by a model to mimic real-world datasets.
    """

    dec: Required[float]
    """
    Barycentric declination of the source in International Celestial Reference
    System (ICRS) at the reference epoch, in degrees.
    """

    ra: Required[float]
    """
    Barycentric right ascension of the source in the International Celestial
    Reference System (ICRS) frame at the reference epoch, in degrees.
    """

    source: Required[str]
    """Source of the data."""

    star_epoch: Required[Annotated[float, PropertyInfo(alias="starEpoch")]]
    """
    Reference epoch to which the astrometric source parameters are referred,
    expressed as Julian Year in Barycentric Coordinate Time (TCB).
    """

    aavso_vsx_id: Annotated[int, PropertyInfo(alias="aavsoVsxId")]
    """
    The American Association of Variable Star Observers (AAVSO) Variable Star Index
    (VSX) (VX) object ID of this object.
    """

    abgmag: float
    """Optical AB g magnitude."""

    abgmag_origin: Annotated[str, PropertyInfo(alias="abgmagOrigin")]
    """Catalog of origin of optical AB g magnitude."""

    abgmag_unc: Annotated[float, PropertyInfo(alias="abgmagUnc")]
    """Uncertainty of optical AB g magnitude."""

    abimag: float
    """Optical AB i magnitude."""

    abimag_origin: Annotated[str, PropertyInfo(alias="abimagOrigin")]
    """Catalog of origin of optical AB i magnitude."""

    abimag_unc: Annotated[float, PropertyInfo(alias="abimagUnc")]
    """Uncertainty of optical AB i magnitude."""

    abrmag: float
    """Optical AB r magnitude."""

    abrmag_origin: Annotated[str, PropertyInfo(alias="abrmagOrigin")]
    """Catalog of origin of optical AB r magnitude."""

    abrmag_unc: Annotated[float, PropertyInfo(alias="abrmagUnc")]
    """Uncertainty of optical AB r magnitude."""

    abymag: float
    """Optical AB y magnitude."""

    abymag_origin: Annotated[str, PropertyInfo(alias="abymagOrigin")]
    """Catalog of origin of optical AB y magnitude."""

    abymag_unc: Annotated[float, PropertyInfo(alias="abymagUnc")]
    """Uncertainty of optical AB y magnitude."""

    abzmag: float
    """Optical AB z magnitude."""

    abzmag_origin: Annotated[str, PropertyInfo(alias="abzmagOrigin")]
    """Catalog of origin of optical AB z magnitude."""

    abzmag_unc: Annotated[float, PropertyInfo(alias="abzmagUnc")]
    """Uncertainty of optical AB z magnitude."""

    all_wis_ecc_ind: Annotated[str, PropertyInfo(alias="allWISEccInd")]
    """Contamination and confusion indicator in AllWISE."""

    all_wise_id: Annotated[str, PropertyInfo(alias="allWISEId")]
    """
    The designation of this object in the All Wide-field Infrared Survey Explorer
    (AllWISE) catalog (AL).
    """

    all_wis_ena_ind: Annotated[int, PropertyInfo(alias="allWISEnaInd")]
    """Active deblending indicator in AllWISE."""

    all_wis_eph_qual_ind: Annotated[str, PropertyInfo(alias="allWISEphQualInd")]
    """Photometric quality indicator in AllWISE."""

    apass_id: Annotated[str, PropertyInfo(alias="apassId")]
    """
    The American Association of Variable Star Observers (AAVSO) Photometric All-Sky
    Survey (APASS) (AP) name of this object.
    """

    astrometric_excess_noise: Annotated[float, PropertyInfo(alias="astrometricExcessNoise")]
    """Astrometric excess noise in the Gaia catalog measured in milliarcseconds."""

    astrometric_excess_noise_sig: Annotated[float, PropertyInfo(alias="astrometricExcessNoiseSig")]
    """Astrometric excess noise sigma in Gaia."""

    bmag: float
    """Optical Johnson B magnitude measured in magnitudes."""

    bmag_origin: Annotated[str, PropertyInfo(alias="bmagOrigin")]
    """Catalog of origin of optical Johnson B magnitude (AP, CR, HI)."""

    bmag_unc: Annotated[float, PropertyInfo(alias="bmagUnc")]
    """Uncertainty of optical Johnson B magnitude measured in magnitudes."""

    bpmag: float
    """Gaia optical photometric Bp-band in the Vega scale measured in magnitudes."""

    bpmag_unc: Annotated[float, PropertyInfo(alias="bpmagUnc")]
    """Gaia optical Bp-band uncertainty in the Vega scale measured in magnitudes."""

    carrasco_cat_id: Annotated[int, PropertyInfo(alias="carrascoCatId")]
    """The Carrasco catalog (CR) identifier of this object."""

    cat_version: Annotated[str, PropertyInfo(alias="catVersion")]
    """The version of the catalog associated with this object."""

    cat_wise2020_id: Annotated[str, PropertyInfo(alias="catWise2020Id")]
    """The CatWISE2020 (CA) catalog source ID of this object."""

    dec_unc: Annotated[float, PropertyInfo(alias="decUnc")]
    """
    Uncertainty of the declination of the source, in milliarcseconds, at the
    reference epoch.
    """

    ducati_cat_id: Annotated[str, PropertyInfo(alias="ducatiCatId")]
    """The Ducati catalog (DU) name of this object."""

    gaiadr3_cat_id: Annotated[int, PropertyInfo(alias="gaiadr3CatId")]
    """The source ID of this object in the Gaia DR3 Catalog (GA)."""

    gmag: float
    """Gaia optical photometric G-band in the Vega scale measured in magnitudes."""

    gmag_unc: Annotated[float, PropertyInfo(alias="gmagUnc")]
    """
    Gaia optical photometric G-band uncertainty in the Vega scale measured in
    magnitudes.
    """

    gnc_cat_id: Annotated[int, PropertyInfo(alias="gncCatId")]
    """The ID of this object in the Guidance and Navigation Control (GNC) Catalog.

    If this field is populated it shall match the csId field.
    """

    healpix_index: Annotated[int, PropertyInfo(alias="healpixIndex")]
    """The Healpix index.

    Consumers should contact the provider for details on the indexing scheme.
    """

    hip_cat_id: Annotated[int, PropertyInfo(alias="hipCatId")]
    """The HIP ID of this object in the Hipparcos Catalog (HI)."""

    hmag: float
    """
    Near-infrared photometric H-band magnitude in the Vega scale measured in
    magnitudes.
    """

    hmag_origin: Annotated[str, PropertyInfo(alias="hmagOrigin")]
    """
    Near-infrared photometric H-band catalog of origin in the Vega scale (TP, UC,
    UL, UP, VH).
    """

    hmag_unc: Annotated[float, PropertyInfo(alias="hmagUnc")]
    """
    Near-infrared photometric H-band magnitude uncertainty in the Vega scale
    measured in magnitudes.
    """

    imag: float
    """Optical Johnson I magnitude measured in magnitudes."""

    imag_origin: Annotated[str, PropertyInfo(alias="imagOrigin")]
    """Catalog of origin of optical Johnson I magnitude (CR, GA, HI)."""

    imag_unc: Annotated[float, PropertyInfo(alias="imagUnc")]
    """Uncertainty of optical Johnson I magnitude measured in magnitudes."""

    jmag: float
    """
    Near-infrared photometric J-band magnitude in the Vega scale measured in
    magnitudes.
    """

    jmag_origin: Annotated[str, PropertyInfo(alias="jmagOrigin")]
    """
    Near-infrared photometric J-band catalog of origin in the Vega scale (TP, UH,
    UL, UP, VH).
    """

    jmag_unc: Annotated[float, PropertyInfo(alias="jmagUnc")]
    """
    Near-infrared photometric J-band magnitude uncertainty in the Vega scale
    measured in magnitudes.
    """

    kmag: float
    """
    Near-infrared photometric K-band magnitude in the Vega scale measured in
    magnitudes.
    """

    kmag_origin: Annotated[str, PropertyInfo(alias="kmagOrigin")]
    """
    Near-infrared photometric K-band catalog of origin in the Vega scale (TP, UC,
    UH, UL, UP, VH).
    """

    kmag_unc: Annotated[float, PropertyInfo(alias="kmagUnc")]
    """
    Near-infrared photometric K-band magnitude uncertainty in the Vega scale
    measured in magnitudes.
    """

    morphology_ind: Annotated[int, PropertyInfo(alias="morphologyInd")]
    """Morphology indicator.

    Consumers should contact the provider for details on the specifications.
    """

    mult_flag: Annotated[bool, PropertyInfo(alias="multFlag")]
    """Flag indicating that this is a multiple object source."""

    multiplicity: str
    """Identifier indicating multiplicity is detected.

    Consumers should contact the provider for details on the specifications.
    """

    neighbor_dec: Annotated[float, PropertyInfo(alias="neighborDec")]
    """Dec of nearest neighbor measured in degrees."""

    neighbor_distance: Annotated[float, PropertyInfo(alias="neighborDistance")]
    """Distance between source and nearest neighbor, in arcseconds."""

    neighbor_flag: Annotated[bool, PropertyInfo(alias="neighborFlag")]
    """
    Flag indicating that the nearest catalog neighbor is closer than 4.6 arcseconds.
    """

    neighbor_id: Annotated[int, PropertyInfo(alias="neighborId")]
    """The catalog ID of the nearest neighbor to this source."""

    neighbor_ra: Annotated[float, PropertyInfo(alias="neighborRa")]
    """RA of nearest neighbor measured in degrees."""

    non_single_star: Annotated[str, PropertyInfo(alias="nonSingleStar")]
    """
    Identifier indicating the source is a non-single star in gaia (additional
    information is available in non-single star tables. Consumers should contact the
    provider for details on the specifications).
    """

    num_neighbors: Annotated[int, PropertyInfo(alias="numNeighbors")]
    """Number of neighbors."""

    origin: str
    """
    Originating system or organization which produced the data, if different from
    the source. The origin may be different than the source if the source was a
    mediating system which forwarded the data on behalf of the origin system. If
    null, the source may be assumed to be the origin.
    """

    pan_starrs_id: Annotated[int, PropertyInfo(alias="panStarrsId")]
    """
    The Panoramic Survey Telescope and Rapid Response System (Pan-STARRS) (PS)
    object ID.
    """

    parallax: float
    """Absolute stellar parallax of the source, in milliarcseconds."""

    parallax_unc: Annotated[float, PropertyInfo(alias="parallaxUnc")]
    """Uncertainty of the stellar parallax, in milliarcseconds."""

    pmdec: float
    """
    Proper motion in declination of the source, in milliarcseconds per year, at the
    reference epoch.
    """

    pmdec_unc: Annotated[float, PropertyInfo(alias="pmdecUnc")]
    """Uncertainty of proper motion in declination, in milliarcseconds per year."""

    pmra: float
    """
    Proper motion in right ascension of the source, in milliarcseconds per year, at
    the reference epoch.
    """

    pmra_unc: Annotated[float, PropertyInfo(alias="pmraUnc")]
    """Uncertainty of proper motion in right ascension, in milliarcseconds per year."""

    pm_unc_flag: Annotated[bool, PropertyInfo(alias="pmUncFlag")]
    """
    Flag indicating that the proper motion uncertainty in either ra or dec is
    greater than 10 milliarcseconds per year.
    """

    pos_unc_flag: Annotated[bool, PropertyInfo(alias="posUncFlag")]
    """
    Flag indicating that the position uncertainty in either ra or dec is greater
    than 100 milliarcseconds.
    """

    ps1astrometry_correction_flag: Annotated[int, PropertyInfo(alias="ps1astrometryCorrectionFlag")]
    """Astrometry correction flag in Pan-STARRS."""

    ps1_obj_info_flag: Annotated[int, PropertyInfo(alias="ps1ObjInfoFlag")]
    """Object information flag in Pan-STARRS."""

    ps1_quality_flag: Annotated[int, PropertyInfo(alias="ps1QualityFlag")]
    """Quality flag in Pan-STARRS."""

    ra_unc: Annotated[float, PropertyInfo(alias="raUnc")]
    """
    Uncertainty of the right ascension of the source, in milliarcseconds, at the
    reference epoch.
    """

    rmag: float
    """Optical Johnson R magnitude measured in magnitudes."""

    rmag_origin: Annotated[str, PropertyInfo(alias="rmagOrigin")]
    """Catalog of origin of the Optical Johnson R magnitude (CR, GA)."""

    rmag_unc: Annotated[float, PropertyInfo(alias="rmagUnc")]
    """Uncertainty of the Optical Johnson R magnitude measured in magnitudes."""

    rpmag: float
    """Gaia optical Rp-band in the Vega scale measured in magnitudes."""

    rpmag_unc: Annotated[float, PropertyInfo(alias="rpmagUnc")]
    """
    Gaia optical photometric Rp-band uncertainty in the Vega scale measured in
    magnitudes.
    """

    ruwe: float
    """RUWE in Gaia."""

    sda_cat_id: Annotated[int, PropertyInfo(alias="sdaCatId")]
    """The ID of this object in the Space Domain Awareness (SDA) Catalog.

    If this field is populated it shall match the csId field.
    """

    sgmag: float
    """
    Original G magnitude if the source is in Gaia, otherwise the magnitude is
    converted from other photometric passbands, when possible, measured in
    magnitudes.
    """

    sgmag_unc: Annotated[float, PropertyInfo(alias="sgmagUnc")]
    """Uncertainty of sgmag measured in magnitudes."""

    shift: float
    """Photocentric shift caused by neighbors, in arcseconds."""

    shift_flag: Annotated[bool, PropertyInfo(alias="shiftFlag")]
    """Flag indicating that the photocentric shift is greater than 50 milliarcseconds."""

    shift_fwhm1: Annotated[float, PropertyInfo(alias="shiftFWHM1")]
    """Photocentric shift caused by neighbors, in arcseconds.

    This value is constrained to a Point Spread Function (PSF) with Full Width at
    Half Maximum (FWHM) of one arcsecond.
    """

    shift_fwhm6: Annotated[float, PropertyInfo(alias="shiftFWHM6")]
    """Photocentric shift caused by neighbors, in arcseconds.

    This value is constrained to a Point Spread Function (PSF) with Full Width at
    Half Maximum (FWHM) of six arcseconds.
    """

    sky_mapper_id: Annotated[int, PropertyInfo(alias="skyMapperId")]
    """The SkyMapper (SK) catalog object ID."""

    two_mass_id: Annotated[str, PropertyInfo(alias="twoMASSId")]
    """
    The designation of this object in the Two Micron All Sky Survey (2MASS) Point
    Source Catalog (TP).
    """

    two_mass_ph_qual_ind: Annotated[str, PropertyInfo(alias="twoMassPHQualInd")]
    """Photometric (PH) quality indicator in 2MASS PSC."""

    two_mass_read_flag: Annotated[str, PropertyInfo(alias="twoMassReadFlag")]
    """Read flag in 2MASS PSC."""

    two_mass_xsc_id: Annotated[str, PropertyInfo(alias="twoMassXscId")]
    """
    The Two Micron All Sky Survey (2MASS) Extended Source Catalog (XSC) (TX)
    designation of this object.
    """

    tycho_dsc_id: Annotated[int, PropertyInfo(alias="tychoDscId")]
    """
    The Tycho Double Star Catalog (TD) identifier (specified as Tycho-2 ID) of this
    object.
    """

    uhs_id: Annotated[int, PropertyInfo(alias="uhsId")]
    """
    The United Kingdom Infrared Telescope (UKIRT) Hemispheric Survey (UHS) (UH)
    source ID of this object.
    """

    ukidss_gcs_id: Annotated[int, PropertyInfo(alias="ukidssGCSId")]
    """
    The United Kingdom Infrared Deep Sky Survey (UKIDSS) Galactic Clusters Survey
    (GCS) (UC) source ID of this object.
    """

    ukidss_gps_id: Annotated[int, PropertyInfo(alias="ukidssGPSId")]
    """
    The United Kingdom Infrared Deep Sky Survey (UKIDSS) Galactic Plane Survey (GPS)
    (UP) source ID of this object.
    """

    ukidss_las_id: Annotated[int, PropertyInfo(alias="ukidssLASId")]
    """
    The United Kingdom Infrared Deep Sky Survey (UKIDSS) Large Area Survey (LAS)
    (UL) source ID of this object.
    """

    var_flag: Annotated[bool, PropertyInfo(alias="varFlag")]
    """Flag indicating that the source exhibits variable magnitude."""

    variability: str
    """Identifier indicating variability is present in the photometric data.

    Consumers should contact the provider for details on the specifications.
    """

    vhs_id: Annotated[int, PropertyInfo(alias="vhsId")]
    """
    The Visible and Infrared Survey Telescope for Astronomy (VISTA) Hemisphere
    Survey (VHS) (VS) source ID of this object.
    """

    vmag: float
    """Optical Johnson V magnitude measured in magnitudes."""

    vmag_origin: Annotated[str, PropertyInfo(alias="vmagOrigin")]
    """Catalog of origin of Optical Johnson V magnitude (AP, CR, DU, GA, HI)."""

    vmag_unc: Annotated[float, PropertyInfo(alias="vmagUnc")]
    """Uncertainty of the Optical Johnson V magnitude measured in magnitudes."""

    w1mag: float
    """
    Mid-infrared photometric W1-band (3.4 microns) magnitude in the Vega system
    measured in magnitudes.
    """

    w1mag_origin: Annotated[str, PropertyInfo(alias="w1magOrigin")]
    """
    Mid-infrared photometric W1-band (3.4 microns) catalog of origin in the Vega
    system (AL, CA).
    """

    w1mag_unc: Annotated[float, PropertyInfo(alias="w1magUnc")]
    """
    Mid-infrared photometric W1-band (3.4 microns) magnitude uncertainty in the Vega
    system measured in magnitudes.
    """

    w1sat: float
    """
    Mid-infrared photometric W1-band (3.4 microns) saturated pixel fraction in the
    Vega system.
    """

    w2mag: float
    """
    Mid-infrared photometric W2-band (4.6 microns) magnitude in the Vega system
    measured in magnitudes.
    """

    w2mag_origin: Annotated[str, PropertyInfo(alias="w2magOrigin")]
    """
    Mid-infrared photometric W2-band (4.6 microns) catalog of origin in the Vega
    system (AL, CA).
    """

    w2mag_unc: Annotated[float, PropertyInfo(alias="w2magUnc")]
    """
    Mid-infrared photometric W2-band (4.6 microns) magnitude uncertainty in the Vega
    system measured in magnitudes.
    """

    w2sat: float
    """
    Mid-infrared photometric W2-band (4.6 microns) saturated pixel fraction in the
    Vega system.
    """

    w3mag: float
    """
    Mid-infrared photometric W3-band (12 microns) magnitude in the Vega system
    measured in magnitudes.
    """

    w3mag_origin: Annotated[str, PropertyInfo(alias="w3magOrigin")]
    """
    Mid-infrared photometric W3-band (12 microns) catalog of origin in the Vega
    system (AL).
    """

    w3mag_unc: Annotated[float, PropertyInfo(alias="w3magUnc")]
    """
    Mid-infrared photometric W3-band (12 microns) magnitude uncertainty in the Vega
    system measured in magnitudes.
    """

    w3sat: float
    """
    Mid-infrared photometric W3-band (12 microns) saturated pixel fraction in the
    Vega system.
    """

    w4mag: float
    """
    Mid-infrared photometric W4-band (22 microns) magnitude in the Vega system
    measured in magnitudes.
    """

    w4mag_origin: Annotated[str, PropertyInfo(alias="w4magOrigin")]
    """
    Mid-infrared photometric W4-band (22 microns) catalog of origin in the Vega
    system (AL).
    """

    w4mag_unc: Annotated[float, PropertyInfo(alias="w4magUnc")]
    """
    Mid-infrared photometric W4-band (22 microns) magnitude uncertainty in the Vega
    system measured in magnitudes.
    """

    w4sat: float
    """
    Mid-infrared photometric W4-band (22 microns) saturated pixel fraction in the
    Vega system.
    """

    wds_cat_id: Annotated[str, PropertyInfo(alias="wdsCatId")]
    """The Washington Double Star Catalog (WD) identifier of this object."""
